# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import character_pb2 as character__pb2


class GOTCharacterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCharacter = channel.unary_unary(
                '/GOTCharacter/GetCharacter',
                request_serializer=character__pb2.CharacterRequest.SerializeToString,
                response_deserializer=character__pb2.CharacterResponse.FromString,
                )


class GOTCharacterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GOTCharacterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacter,
                    request_deserializer=character__pb2.CharacterRequest.FromString,
                    response_serializer=character__pb2.CharacterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GOTCharacter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GOTCharacter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GOTCharacter/GetCharacter',
            character__pb2.CharacterRequest.SerializeToString,
            character__pb2.CharacterResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
