# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: character.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='character.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63haracter.proto\"T\n\x10\x43haracterRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1a\n\x05house\x18\x02 \x01(\x0e\x32\x0b.Allegiance\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"~\n\tCharacter\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1a\n\x05house\x18\x04 \x01(\x0e\x32\x0b.Allegiance\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x10\n\x08religion\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\"3\n\x11\x43haracterResponse\x12\x1e\n\ncharacters\x18\x01 \x03(\x0b\x32\n.Character*\x7f\n\nAllegiance\x12\t\n\x05STARK\x10\x00\x12\t\n\x05\x41RRYN\x10\x01\x12\r\n\tBARATHEON\x10\x02\x12\t\n\x05TULLY\x10\x03\x12\x0b\n\x07GREYJOY\x10\x04\x12\r\n\tLANNISTER\x10\x05\x12\t\n\x05TYREL\x10\x06\x12\x0b\n\x07MARTELL\x10\x07\x12\r\n\tTARGARYEN\x10\x08\x32\x45\n\x0cGOTCharacter\x12\x35\n\x0cGetCharacter\x12\x11.CharacterRequest\x1a\x12.CharacterResponseb\x06proto3'
)

_ALLEGIANCE = _descriptor.EnumDescriptor(
  name='Allegiance',
  full_name='Allegiance',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STARK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ARRYN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BARATHEON', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TULLY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GREYJOY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LANNISTER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYREL', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARTELL', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TARGARYEN', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=286,
  serialized_end=413,
)
_sym_db.RegisterEnumDescriptor(_ALLEGIANCE)

Allegiance = enum_type_wrapper.EnumTypeWrapper(_ALLEGIANCE)
STARK = 0
ARRYN = 1
BARATHEON = 2
TULLY = 3
GREYJOY = 4
LANNISTER = 5
TYREL = 6
MARTELL = 7
TARGARYEN = 8



_CHARACTERREQUEST = _descriptor.Descriptor(
  name='CharacterRequest',
  full_name='CharacterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='CharacterRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='house', full_name='CharacterRequest.house', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='CharacterRequest.max_results', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=103,
)


_CHARACTER = _descriptor.Descriptor(
  name='Character',
  full_name='Character',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Character.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='Character.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Character.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='house', full_name='Character.house', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='Character.age', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='religion', full_name='Character.religion', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='Character.email', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=231,
)


_CHARACTERRESPONSE = _descriptor.Descriptor(
  name='CharacterResponse',
  full_name='CharacterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='characters', full_name='CharacterResponse.characters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=284,
)

_CHARACTERREQUEST.fields_by_name['house'].enum_type = _ALLEGIANCE
_CHARACTER.fields_by_name['house'].enum_type = _ALLEGIANCE
_CHARACTERRESPONSE.fields_by_name['characters'].message_type = _CHARACTER
DESCRIPTOR.message_types_by_name['CharacterRequest'] = _CHARACTERREQUEST
DESCRIPTOR.message_types_by_name['Character'] = _CHARACTER
DESCRIPTOR.message_types_by_name['CharacterResponse'] = _CHARACTERRESPONSE
DESCRIPTOR.enum_types_by_name['Allegiance'] = _ALLEGIANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CharacterRequest = _reflection.GeneratedProtocolMessageType('CharacterRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHARACTERREQUEST,
  '__module__' : 'character_pb2'
  # @@protoc_insertion_point(class_scope:CharacterRequest)
  })
_sym_db.RegisterMessage(CharacterRequest)

Character = _reflection.GeneratedProtocolMessageType('Character', (_message.Message,), {
  'DESCRIPTOR' : _CHARACTER,
  '__module__' : 'character_pb2'
  # @@protoc_insertion_point(class_scope:Character)
  })
_sym_db.RegisterMessage(Character)

CharacterResponse = _reflection.GeneratedProtocolMessageType('CharacterResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHARACTERRESPONSE,
  '__module__' : 'character_pb2'
  # @@protoc_insertion_point(class_scope:CharacterResponse)
  })
_sym_db.RegisterMessage(CharacterResponse)



_GOTCHARACTER = _descriptor.ServiceDescriptor(
  name='GOTCharacter',
  full_name='GOTCharacter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=415,
  serialized_end=484,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCharacter',
    full_name='GOTCharacter.GetCharacter',
    index=0,
    containing_service=None,
    input_type=_CHARACTERREQUEST,
    output_type=_CHARACTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOTCHARACTER)

DESCRIPTOR.services_by_name['GOTCharacter'] = _GOTCHARACTER

# @@protoc_insertion_point(module_scope)
